# Generated by Django 2.2 on 2021-09-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20210926_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='notes',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
