# Generated by Django 2.2 on 2021-09-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20210926_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='notes',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
    ]
