# Generated by Django 3.2.6 on 2021-11-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_auto_20210926_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
